/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

/**
 *
 * @author igor
 */
public class Apresentacao extends javax.swing.JFrame {

    /**
     * Creates new form Apresentacao
     */
    public Apresentacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLimpar = new javax.swing.JButton();
        jButtonSomatorio = new javax.swing.JButton();
        jButtonDecremento = new javax.swing.JButton();
        jButtonCleaner = new javax.swing.JButton();
        jButtonNumero1 = new javax.swing.JButton();
        jButtonNumero2 = new javax.swing.JButton();
        jButtonNumero3 = new javax.swing.JButton();
        jButtonSomar = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonNumero6 = new javax.swing.JButton();
        jButtonNumero4 = new javax.swing.JButton();
        jButtonNumero5 = new javax.swing.JButton();
        jButtonNumero7 = new javax.swing.JButton();
        jButtonNumero8 = new javax.swing.JButton();
        jButtonNumero9 = new javax.swing.JButton();
        jButtonMulti = new javax.swing.JButton();
        jTextFieldDisplay = new javax.swing.JTextField();
        jButtonMR = new javax.swing.JButton();
        jButtonVirgula = new javax.swing.JButton();
        jButtonNumero0 = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonNumero3KeyPressed(evt);
            }
        });

        jButtonLimpar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonLimpar.setText("CE");

        jButtonSomatorio.setText("M+");
        jButtonSomatorio.setAlignmentX(0.5F);

        jButtonDecremento.setText("M-");
        jButtonDecremento.setAlignmentX(0.5F);

        jButtonCleaner.setText("MC");
        jButtonCleaner.setAlignmentX(0.5F);

        jButtonNumero1.setText("1");
        jButtonNumero1.setAlignmentX(0.5F);

        jButtonNumero2.setText("2");
        jButtonNumero2.setAlignmentX(0.5F);

        jButtonNumero3.setText("3");
        jButtonNumero3.setAlignmentX(0.5F);

        jButtonSomar.setText("+");
        jButtonSomar.setAlignmentX(0.5F);

        jButtonSubtracao.setText("-");
        jButtonSubtracao.setAlignmentX(0.5F);

        jButtonNumero6.setText("6");
        jButtonNumero6.setAlignmentX(0.5F);

        jButtonNumero4.setText("4");
        jButtonNumero4.setAlignmentX(0.5F);

        jButtonNumero5.setText("5");
        jButtonNumero5.setAlignmentX(0.5F);

        jButtonNumero7.setText("7");
        jButtonNumero7.setAlignmentX(0.5F);

        jButtonNumero8.setText("8");
        jButtonNumero8.setAlignmentX(0.5F);

        jButtonNumero9.setText("9");
        jButtonNumero9.setAlignmentX(0.5F);

        jButtonMulti.setText("*");
        jButtonMulti.setAlignmentX(0.5F);

        jTextFieldDisplay.setEditable(false);
        jTextFieldDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDisplay.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jButtonMR.setText("MR");
        jButtonMR.setAlignmentX(0.5F);

        jButtonVirgula.setText(".");
        jButtonVirgula.setAlignmentX(0.5F);

        jButtonNumero0.setText("0");
        jButtonNumero0.setAlignmentX(0.5F);

        jButtonIgual.setText("=");
        jButtonIgual.setAlignmentX(0.5F);

        jButtonDivisao.setText("/");
        jButtonDivisao.setAlignmentX(0.5F);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonNumero4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonNumero5))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jButtonSomatorio)
                                            .addGap(4, 4, 4)
                                            .addComponent(jButtonDecremento))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jButtonNumero1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonNumero2)))
                                    .addGap(6, 6, 6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonCleaner)
                                        .addComponent(jButtonNumero3)
                                        .addComponent(jButtonNumero6)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonNumero7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonNumero8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonNumero9)))
                            .addGap(7, 7, 7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonMulti)
                                .addComponent(jButtonSubtracao)
                                .addComponent(jButtonSomar)
                                .addComponent(jButtonMR)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonLimpar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVirgula)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNumero0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonIgual)
                                .addGap(7, 7, 7)
                                .addComponent(jButtonDivisao)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonCleaner, jButtonDecremento, jButtonDivisao, jButtonIgual, jButtonMR, jButtonMulti, jButtonNumero0, jButtonNumero1, jButtonNumero2, jButtonNumero3, jButtonNumero4, jButtonNumero5, jButtonNumero6, jButtonNumero7, jButtonNumero8, jButtonNumero9, jButtonSomar, jButtonSubtracao, jButtonVirgula});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSomatorio)
                    .addComponent(jButtonDecremento)
                    .addComponent(jButtonCleaner)
                    .addComponent(jButtonMR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumero1)
                    .addComponent(jButtonNumero2)
                    .addComponent(jButtonNumero3)
                    .addComponent(jButtonSomar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubtracao)
                    .addComponent(jButtonNumero6)
                    .addComponent(jButtonNumero4)
                    .addComponent(jButtonNumero5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumero7)
                    .addComponent(jButtonNumero8)
                    .addComponent(jButtonNumero9)
                    .addComponent(jButtonMulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVirgula)
                    .addComponent(jButtonNumero0)
                    .addComponent(jButtonIgual)
                    .addComponent(jButtonDivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNumero3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonNumero3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNumero3KeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apresentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apresentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCleaner;
    private javax.swing.JButton jButtonDecremento;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonMR;
    private javax.swing.JButton jButtonMulti;
    private javax.swing.JButton jButtonNumero0;
    private javax.swing.JButton jButtonNumero1;
    private javax.swing.JButton jButtonNumero2;
    private javax.swing.JButton jButtonNumero3;
    private javax.swing.JButton jButtonNumero4;
    private javax.swing.JButton jButtonNumero5;
    private javax.swing.JButton jButtonNumero6;
    private javax.swing.JButton jButtonNumero7;
    private javax.swing.JButton jButtonNumero8;
    private javax.swing.JButton jButtonNumero9;
    private javax.swing.JButton jButtonSomar;
    private javax.swing.JButton jButtonSomatorio;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JButton jButtonVirgula;
    private javax.swing.JTextField jTextFieldDisplay;
    // End of variables declaration//GEN-END:variables
}
